<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>injectionSelector</key>
	<string>source</string>
	<key>name</key>
	<string>CONSTANTS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b([A-Z][A-Z\d_]+)\b</string>
			<key>name</key>
			<string>variable.other.user-constant</string>
		</dict>
	</array>
	<key>uuid</key>
	<string>857A701C-832A-4C4F-9EFE-EB56C91A5006</string>
</dict>
</plist>
